import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

Font.register({
  family: 'Inter',
  src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZg.ttf'
});

const styles = StyleSheet.create({
  page: { fontFamily: 'Inter', padding: 30, fontSize: 11 },
  header: { marginBottom: 20, borderBottom: '1 solid #e2e8f0', paddingBottom: 10 },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#64748b' },
  table: { display: 'flex', width: 'auto' },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#e2e8f0', borderBottomStyle: 'solid', alignItems: 'center', height: 24 },
  tableHeader: { backgroundColor: '#f1f5f9', fontWeight: 'bold' },
  colHari: { width: '15%', paddingHorizontal: 4, fontSize: 10 },
  colJam: { width: '20%', paddingHorizontal: 4, fontSize: 10 },
  colMatkul: { width: '30%', paddingHorizontal: 4, fontSize: 10 },
  colDosen: { width: '25%', paddingHorizontal: 4, fontSize: 10 },
  colRuangan: { width: '10%', paddingHorizontal: 4, fontSize: 10 },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 9, color: '#94a3b8' },
  colorDot: { width: 8, height: 8, borderRadius: 4, marginRight: 4 },
});

interface Schedule {
  id: string;
  mataPelajaran: string;
  namaDosen: string;
  ruangan: string | null;
  waktuMulai: string;
  waktuSelesai: string;
  hari: string;
  sks: number | null;
  warnaKategori: string;
}

export const SchedulePDF = ({ schedules, userName }: { schedules: Schedule[]; userName: string }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>📅 Jadwal Kuliah</Text>
        <Text style={styles.subtitle}>Generated by JADWALIN • {userName}</Text>
        <Text style={styles.subtitle}>{new Date().toLocaleDateString('id-ID', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</Text>
      </View>
      <View style={[styles.tableRow, styles.tableHeader]}>
        <Text style={styles.colHari}>Hari</Text>
        <Text style={styles.colJam}>Jam</Text>
        <Text style={styles.colMatkul}>Mata Kuliah</Text>
        <Text style={styles.colDosen}>Dosen</Text>
        <Text style={styles.colRuangan}>Ruang</Text>
      </View>
      {schedules.map((s) => (
        <View key={s.id} style={styles.tableRow}>
          <Text style={styles.colHari}>{s.hari}</Text>
          <Text style={styles.colJam}>{s.waktuMulai}-{s.waktuSelesai}</Text>
          <Text style={styles.colMatkul}>
            <View style={{ flexDirection: 'row', alignItems: 'center' }}>
              <View style={[styles.colorDot, { backgroundColor: s.warnaKategori ?? '#3B82F6'}]} />
              <Text>{s.mataPelajaran}</Text>
            </View>
          </Text>
          <Text style={styles.colDosen}>{s.namaDosen}</Text>
          <Text style={styles.colRuangan}>{s.ruangan || '-'}</Text>
        </View>
      ))}
      <Text style={styles.footer}>JADWALIN • Generated on {new Date().toLocaleString('id-ID')}</Text>
    </Page>
  </Document>
);